### PR TITLE
Boolean logic, Strings and Character types

### PR DESCRIPTION
**Pull request by WilliamRagstad**
## Changes
* Adds support for Boolean comparisons using the already existing `isTruthy()` method, operands are evaluated if one of them is `true` or `false`. therefore, `[] == [1]` cannot be run, but `[] == false` can and returns true, indicating that `[]` truth-value is `false`.
* Adds support for Boolean negation using the existing `-` symbol, this can be linked to mathematics where negation is indicated by `¬` which is a very similar symbol. This is a simple solution but it can be considered to implement a dedicated operator like `!` For this as in other languages.

## Discussion
Suppose you have a list `list` like in the example below:
```rust
let list = [9, 8, 7, 6]
```
And you want to extract the first element safely by first checking of the list has elements because the `^` operator throws an exception in case the operand is an empty list `Index 0 out of bounds for length 0`. This is at the moment not possible what I know as the language is lacking a `match` or `case` keyword for pattern matching? Therefore one would want to do this using `if` and with this PR, users are able to compare the *truthiness* of the list with a Boolean as follows:
```rust
let first = fn (l) => if (l == true) then (^l) else (null)
```
Now you can select the first element without the need to worry about getting an exception.
```rust
> first(list)
9
> first([])
null
```
The second part of this PR is mostly about to the negation of Boolean expressions. For this I suggest the use of the `-` prefix operator, as it is similar to the `¬` symbol in mathematics. It might wanted to consider using a **dedicated operator** for this, but to do it this way **minimizes** the size of the language and increases **expressiveness** with fewer operators.

### CODE REVIEW

**Comment by mkhan45** [comment]
Hey I really appreciate the PR, but since this is for a school project I'll wait until after it's graded to merge it.

> And you want to extract the first element safely by first checking of the list has elements because the ^ operator throws an exception in case the operand is an empty list Index 0 out of bounds for length 0. This is at the moment not possible what I know as the language is lacking a match or case keyword for pattern matching? Therefore one would want to do this using if and with this PR, users are able to compare the truthiness of the list with a Boolean as follows:

Actually, this is possible. Just use `(l)` as the condition instead of `(l == true)`. I'll still keep the commit since I think it's a helpful addition. The `first` function you constructed is still not possible though, since the language doesn't have null. However, it's not needed anyway since null would be unusable where the real head of a list would be expected, so you'd always have to check for the list to exist first.

The negation of Boolean expressions is a great addition. Thanks!

**Comment by WilliamRagstad** [comment]
> since this is for a school project I'll wait until after it's graded to merge it.

Haha alright, that's completely understandable to be fair ;)
It seems like a sophisticated but fun project! What course is it?

 > Actually, this is possible. Just use (l) as the condition instead of (l == true). I'll still keep the commit since I think it's a helpful addition.

Yeah that's true now when I think about it, you use `isTruthy()` in the evaluation for `if` statement conditions. Then it might be better to change (in `Atom.eq`):
```java
if (this instanceof Bool || rhs instanceof Bool) {
        return (Atom) new Bool(this.isTruthy() == rhs.isTruthy());
}
```
To:
```java
if (this instanceof Bool && rhs instanceof Bool) {
        return (Atom) new Bool(((Bool) this).val == ((Bool) rhs).val);
}
```
Which prevents certain ambiguities for comparison.

> the language doesn't have null

Yeah, I assumed that when the REPL returned null in some cases. Is the language taking more of a **functional** approach then? Functions are first-class so it's not far from a functional language.

**Comment by mkhan45** [comment]
> Is the language taking more of a functional approach then? Functions are first-class so it's not far from a functional language.

Well it doesn't have mutation, meaning that it also lacks iteration. It's not lazy though.

I'm curious to know when the REPL returned null. The codebase has more or less completely left my brain since I worked on it but that's not intended unless I've forgot something critical

**Comment by WilliamRagstad** [comment]
### Strings and Character types
I tinkered a bit more on the project and added support for a character atoms, as well as parsing of strings to lists of characters, meaning expressions like these are now possible:
```rust
> let list = "Hello" + [',', ' '] + "world" + ['!']
"Hello, world!"

> reverse(list)
"!dlrow ,olleH"

> ["foo"]
["foo"]
```
I changed so that if a list only contains `Expr.AtomicExpr` with `Atom.Char` values, the list is formatted as a string instead of using the built in `list.toString()`.

### Discussion
> it doesn't have mutation

I assume that applies when running the interpreter on a script file? Because it is possible to run the following inside the REPL:
```rust
> let x = 1
> x
1

> let x = 2
> x
2
```
> I'm curious to know when the REPL returned null

For example:
```rust
> noIdentifier
null
```

**Comment by mkhan45** [comment]
Strings and characters are a neat addition. Thanks!

### Discussion

So I think of `let` expressions as reassignment instead of mutation, since there's no way to modify a variable in place without reallocating. It's true that `let`assignments  *are* an expression instead of a statement so you can use them to return from other expressions. However reassignments through `let` are local to the scope, so for example this doesn't accomplish much:

```
> let x = 5
> x
5
> [let x = x + 5 for n in [0..5]]
[(), (), (), (), ()]
> x
5
```

Therefore, I think it's fair to say that RustLang doesn't have mutation.

___

As for the nulls, it looks like this block of code in AtomicExpr.eval doesn't behave as expected:
```java
try {
    return variables.get(v.name);
} catch (Exception e) {
    throw new Exception(String.format("Tried to access nonexistent variable %s", v.name));
}
```

I guess it should be more like:
```java
var res = variables.get(v.name);
if (res == null) {
    throw new Exception(String.format("Tried to access nonexistent variable %s", v.name));
}
return res;
```

If you'd like you can add a commit to change this; otherwise I'll just do it after I merge this.

**Comment by WilliamRagstad** [comment]
### Discussion
> there's no way to modify a variable in place without reallocating

Alright that's fair, I like that definition of mutation a lot actually.

> you can add a commit to change this

I did, but not sure if it should be in its own PR or not. This one seems to grow at an accelerating pace.

**Review by mkhan45 — APPROVED** [review]

**Comment by mkhan45** [comment]
It's been graded and I got an A. Thanks for the PR!

**Comment by WilliamRagstad** [comment]
Congratulations man! You're worth it!
Which course is it? Are you planning to continue working on this project?

**Comment by mkhan45** [comment]
Thanks!

The course was actually just intro to CS and OOP, but I needed a few bonus points so I went a little overkill. I'm not planning to continue this project. However, I'd like to design a more complete and useable language in the future, and some of the design will be similar between languages. For example, I really like working with ^ and $ as head and tail operators.

**Pull request merged**
